// Code generated by go-bindata.
// sources:
// ../app/.DS_Store
// ../app/bundle.css
// ../app/bundle.js
// ../app/index.html
// ../app/lib/.DS_Store
// ../app/lib/jquery-2.2.4.min.js
// ../app/lib/oreilly-theme.css
// ../app/lib/thebe.js
// DO NOT EDIT!

package main

import (
	"net/http"
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// AppDs_store reads file data from disk. It returns an error on failure.
func AppDs_store() (*asset, error) {
	path := "/Users/bravomartin/WORK/OREILLY/Satturn/satturn/app/.DS_Store"
	name := "../app/.DS_Store"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// AppBundleCss reads file data from disk. It returns an error on failure.
func AppBundleCss() (*asset, error) {
	path := "/Users/bravomartin/WORK/OREILLY/Satturn/satturn/app/bundle.css"
	name := "../app/bundle.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// AppBundleJs reads file data from disk. It returns an error on failure.
func AppBundleJs() (*asset, error) {
	path := "/Users/bravomartin/WORK/OREILLY/Satturn/satturn/app/bundle.js"
	name := "../app/bundle.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// AppIndexHtml reads file data from disk. It returns an error on failure.
func AppIndexHtml() (*asset, error) {
	path := "/Users/bravomartin/WORK/OREILLY/Satturn/satturn/app/index.html"
	name := "../app/index.html"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// AppLibDs_store reads file data from disk. It returns an error on failure.
func AppLibDs_store() (*asset, error) {
	path := "/Users/bravomartin/WORK/OREILLY/Satturn/satturn/app/lib/.DS_Store"
	name := "../app/lib/.DS_Store"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// AppLibJquery224MinJs reads file data from disk. It returns an error on failure.
func AppLibJquery224MinJs() (*asset, error) {
	path := "/Users/bravomartin/WORK/OREILLY/Satturn/satturn/app/lib/jquery-2.2.4.min.js"
	name := "../app/lib/jquery-2.2.4.min.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// AppLibOreillyThemeCss reads file data from disk. It returns an error on failure.
func AppLibOreillyThemeCss() (*asset, error) {
	path := "/Users/bravomartin/WORK/OREILLY/Satturn/satturn/app/lib/oreilly-theme.css"
	name := "../app/lib/oreilly-theme.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// AppLibThebeJs reads file data from disk. It returns an error on failure.
func AppLibThebeJs() (*asset, error) {
	path := "/Users/bravomartin/WORK/OREILLY/Satturn/satturn/app/lib/thebe.js"
	name := "../app/lib/thebe.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"../app/.DS_Store": AppDs_store,
	"../app/bundle.css": AppBundleCss,
	"../app/bundle.js": AppBundleJs,
	"../app/index.html": AppIndexHtml,
	"../app/lib/.DS_Store": AppLibDs_store,
	"../app/lib/jquery-2.2.4.min.js": AppLibJquery224MinJs,
	"../app/lib/oreilly-theme.css": AppLibOreillyThemeCss,
	"../app/lib/thebe.js": AppLibThebeJs,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"..": &bintree{nil, map[string]*bintree{
		"app": &bintree{nil, map[string]*bintree{
			".DS_Store": &bintree{AppDs_store, map[string]*bintree{}},
			"bundle.css": &bintree{AppBundleCss, map[string]*bintree{}},
			"bundle.js": &bintree{AppBundleJs, map[string]*bintree{}},
			"index.html": &bintree{AppIndexHtml, map[string]*bintree{}},
			"lib": &bintree{nil, map[string]*bintree{
				".DS_Store": &bintree{AppLibDs_store, map[string]*bintree{}},
				"jquery-2.2.4.min.js": &bintree{AppLibJquery224MinJs, map[string]*bintree{}},
				"oreilly-theme.css": &bintree{AppLibOreillyThemeCss, map[string]*bintree{}},
				"thebe.js": &bintree{AppLibThebeJs, map[string]*bintree{}},
			}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}


func assetFS() http.FileSystem {
	for k := range _bintree.Children {
		return http.Dir(k)
	}
	panic("unreachable")
}
